Task7
russov/Md-CD1-30-24 pull request #101
Opened 2024-06-15 15:48 UTC by KostyaTimoshenko

Выполнил задание согласно условию.

2024-06-24 13:40 UTC, russov requested changes

2024-06-24 13:40 UTC, russov commented on Kostya_Timoshenko/Task7/Task7_test/Task7.h
> +        else {
else можно вообще не писать. если зайдет в if то выброситься исключение и не попадет дальше. а если не попадет в if то сразу попадет на return. Просто так немного красивее будет

2024-06-24 13:40 UTC, russov commented on Kostya_Timoshenko/Task7/Task7_test/test.cpp
нету проверок для аварийных ситуаций. таких как выход за пределы вектора

2024-06-24 14:13 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task7/Task7_test/Task7.h
> +        else {
Исправил, спасибо

2024-06-24 14:14 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task7/Task7_test/test.cpp
Добавил ещё два теста

2024-07-01 11:48 UTC, russov approved these changes

2024-07-01 11:48 UTC, merged