Task8
russov/Md-CD1-30-24 pull request #102
Opened 2024-06-24 03:03 UTC by KostyaTimoshenko

Реализовал многопоточное приложение, согласно условию задания.

2024-06-28 16:38 UTC, russov requested changes

2024-06-28 16:38 UTC, russov commented on Kostya_Timoshenko/Task8/Task8/Task8.cpp
> +struct Data_storage { // Data storage structure
для таких веще будет более нативно использовать namespace

2024-06-28 16:38 UTC, russov commented on Kostya_Timoshenko/Task8/Task8/Task8.cpp
> +                data.buffer.pop();
не удалить последний элемент из очереди а не записывать в очередь тот элемент который был вычитан и не влез в очередь

2024-06-28 16:38 UTC, russov commented on Kostya_Timoshenko/Task8/Task8/Task8.cpp
> +    size_t �haractersRead = 0; // Number of characters read
ñ - что это за символ? символ странный, но код работает)

2024-06-28 16:38 UTC, russov commented on Kostya_Timoshenko/Task8/Task8/Task8.cpp
> +            data.bufferNotEmpty.wait(lock, [&] { return !data.buffer.empty() || data.stopRead; }); // Waiting until the buffer is non-empty or the flag is true. This helps the writer thread continue
в учебных целях ок, но для продакшена слишком сложная логика и не уверен, что надежная на 100 процентов.
если я правильно понял смысл в том чтобы записать значение как только оно появиться в буфере. Можешь это не исправлять, думаю что иногда такой подход очень полезный может быть

2024-07-01 18:13 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task8/Task8/Task8.cpp
> +struct Data_storage { // Data storage structure
Исправил, использую теперь пространство имён.

2024-07-01 18:15 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task8/Task8/Task8.cpp
> +                data.buffer.pop();
Исправил, немного так же поменял if и его условие. Не внимательно прочитал условие задание, извиняюсь.

2024-07-01 18:19 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task8/Task8/Task8.cpp
> +    size_t �haractersRead = 0; // Number of characters read
Это (с) русское, видно когда давал переменной имя, использовал русский алфавит, потом наверное увидел что даю на русском, поменял раскладку но не до конца удалил, старое название что напечатал на русском, далее просто копировал название переменной когда использовал её в приложении, по этому везде такой символ, а github отображает так русские символы.

2024-07-01 18:20 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task8/Task8/Task8.cpp
> +            data.bufferNotEmpty.wait(lock, [&] { return !data.buffer.empty() || data.stopRead; }); // Waiting until the buffer is non-empty or the flag is true. This helps the writer thread continue
Да все верно, понял, спасибо.

2024-07-02 08:04 UTC, russov approved these changes

2024-07-02 08:04 UTC, merged