fix .h file
russov/Md-CD1-30-24 pull request #21
Opened 2024-03-29 17:13 UTC by Ri4ardsal

Удалил в игноре строку *_h.h

2024-04-08 10:52 UTC, russov requested changes

2024-04-08 10:52 UTC, russov commented on Vlad_Salnikov/Task2/file.cpp
> +void readFile(std::vector<int>& numbers)
непонятно зачем тут этот метод. Он что-то вычитывает из файла, сохраняет в переменную и в конце удаляет переменную.

2024-04-08 10:52 UTC, russov commented on Vlad_Salnikov/Task2/numCheck.cpp
> + int numCheck(int num)
метод называется как проверка значения на правильный ввод символа, но здесь же и читает с консоли. Архитектурно это неверно. если ты хочешь сделать проверку, то просто организуешь в одном месте чтение с консоли, а в другом проверку.
По названию этой функции, я бы ожидал true/false, но не int.

2024-04-08 10:52 UTC, russov commented on Vlad_Salnikov/Task2/Task2.cpp
> +	while (choise != 0)
1) while(choise)
2) choice - мы тут учим не английский, но все же красивее когда нет ошибок))

2024-04-08 10:52 UTC, russov commented on Vlad_Salnikov/Task2/Task2.cpp
> +			choise = 0;
если ты хочешь выйти из цикла используй return

2024-04-08 10:52 UTC, russov commented on Vlad_Salnikov/Task2/Task2.cpp
> +			choise = 1000;
вообще не понял, зачем тут это. но магических чисел в коде не должно быть. Пересмотри логику пожалуйста.

2024-04-08 10:52 UTC, russov commented on Vlad_Salnikov/Task2/file.cpp
> +		//break;
не оставляй таких комментариев

2024-04-14 03:11 UTC, Ri4ardsal commented on Vlad_Salnikov/Task2/file.cpp
> +void readFile(std::vector<int>& numbers)
в этом методе считывается строки из файла в стринг типе и заполняют стринговый вектор, затем используя стринговый вектор, мы заполняем основной интовый с помощью stoi.

2024-04-14 03:42 UTC, Ri4ardsal commented on Vlad_Salnikov/Task2/numCheck.cpp
> + int numCheck(int num)
Изменил название метода. Но здесь нужен int, потому что этот метод возвращает значение новой переменной, если была допущена ошибка при вводе. Создавая этот метод, я пытался избежать создавать циклы повторения ввода для каждой проверяемой переменной.

2024-04-14 03:45 UTC, Ri4ardsal commented on Vlad_Salnikov/Task2/Task2.cpp
> +			choise = 0;
Здесь нельзя использовать return. Switch находится в теле функции main.![Screenshot_2024-04-14-05-53-27-033_com.brave.browser-edit.jpg](https://github.com/russov/Md-CD1-30-24/assets/144533079/e7de336a-ce8b-480c-b983-c0eb3421aaa9)

2024-04-15 09:57 UTC, russov requested changes

2024-04-15 09:57 UTC, russov commented on Vlad_Salnikov/Task2/file.cpp
> +	std::ifstream file;
Наверное ofstrem?

2024-04-15 09:57 UTC, russov commented on Vlad_Salnikov/Task2/file.cpp
> +	std::ifstream file;
ofstream?

2024-04-15 09:57 UTC, russov commented on Vlad_Salnikov/Task2/main.cpp
Похоже, файл был переименован, но в проекте не изменен, и у меня не видит файла Task2.
Наверное Task2 надо переименовать в main.
![image](https://github.com/russov/Md-CD1-30-24/assets/5598641/28258707-db4e-4a64-ae80-e76cb600fef0)

2024-04-15 09:57 UTC, russov commented on Vlad_Salnikov/Task2/numCheck.cpp
> + int checkingAndCorrectingInputErrors(int num)
Я имел ввиду, что если метод называется check, то он должен возвращать bool, то есть есть проверка то она возвращает результат проверку хорошо либо плохо, а здесь возвращается число. здесь у меня претензия к названию метода, либо к возвращаемому значению, название не соответствует ожиданию.
И с точки зрения архитектуры выглядит не очень не очень: в двух местах происходит чтение из консоли, лучше чтобы читалось только в одном, а то получается дублирование кода.

2024-04-15 09:57 UTC, russov commented on Vlad_Salnikov/Task2/file.cpp
> +void readFile(std::vector<int>& numbers)
Я понял. Был не прав, но в этом и проблема, что результат записывается в параметр, тут лучше возвращать вектор из функции, потому что можно запутаться и сразу не очевидно что это выходной параметр а не входной. 
Такой подход существует, но не стоит им злоупотреблять, потому что сложнее читать и понимать смысл функции.

2024-04-15 09:57 UTC, russov commented on Vlad_Salnikov/Task2/file.cpp
> +	file.open(file_name + ".txt");
ни везде есть проверка на открытие файла.

2024-04-15 09:57 UTC, russov commented on Vlad_Salnikov/Task2/main.cpp
> +			readFile(numbers);
где-то не происходит очистка переменной
![image](https://github.com/russov/Md-CD1-30-24/assets/5598641/cb8c4798-6aea-403a-b408-4a1cf9091bf1)

2024-04-15 09:57 UTC, russov commented on Vlad_Salnikov/Task2/Task2.cpp
> +			choise = 0;
здесь break выходит из switch а не из цикла.
Здесь используется int переменная, чтобы выйти из цикла когда она равна нулю. Это неочевидное ожидание поведения. почему сетится 1000 (choice{ 1000 }) а не 100? магические числа стоит избегать. В лучшем случае можно использовать bool переменную, как флаг, надо продолжать или не надо продолжать цикл.
Если очень хочется оставить эту логику, то можно сделать чтобы choice присваивалось значение введенное в терминале, потому что choice = 0; это очень плохо пахнет и не понятно с первого взгляда что он делает.
В данном случае return очень хорошо подойдет. И будет более гармонично смотреться. Цикл можно сделать бесконечным пока не нажмут 0 и не произойдет выход по return.

2024-04-15 10:01 UTC, russov commented on Vlad_Salnikov/Task2/Task2.cpp
> +			choise = 0;
Во первых приложение не собралось у меня. Я в комментах написал, что не так было, но следубщий раз, проверяй перед коммитом, не буду даже смотреть код если не соберется.
Проблема с именованием функций и файлов не исправлена.
Вывод на экран реализована и на русской и на английском, стремись к одинаковому стилю везде. если русский то русский везде, аналогично с английским, надо придерживаться одного стиля.
Чтобы не было дублирования кода, можно одинаковый код вынести в отдельный файл.

2024-04-19 20:26 UTC, russov approved these changes

2024-04-19 20:26 UTC, merged