Tast_2_Kluev
russov/Md-CD1-30-24 pull request #28
Opened 2024-04-02 20:02 UTC by C0rnFl0wer

2024-04-08 11:44 UTC, russov commented
В целом все норм. 
Но если бы разнес каждую задачу в отдельную функцию было бы красивее. Но можешь не исправлять.
И глобально приложение выглядит очень громоздким, работает, очень много лишнего кода, но как для первого раза все ок, просто следующий раз старайся писать код более простой,

2024-04-08 11:44 UTC, russov requested changes

2024-04-08 11:44 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    int SIZE;
не используй большие буквы для названия локальных переменных

2024-04-08 11:44 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    ofstream Lesson_3;
плохое название для переменной. 
И старайся придерживаться одного стиля: в одном месте переменная называлась с большой буквы в другом с маленькой, в третьем вообще все буквы большие

2024-04-08 11:44 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    //string path = "D:\git_(trashbucket)\lesson_3\read.txt";
удали ненужные комментарии

2024-04-08 11:44 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    delete New_Arrr_of_Numbers;
потерялись квадратные скобки

2024-04-08 11:44 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    while (!(cin >> SIZE))
При вводе отрицательного числа приложение, повисает

2024-04-08 11:48 UTC, russov requested changes

2024-04-08 11:48 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +int main()
не реализовано чтение файла в обратную сторону

2024-04-11 15:13 UTC, C0rnFl0wer commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    int SIZE;
Исправил

2024-04-11 15:14 UTC, C0rnFl0wer commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    //string path = "D:\git_(trashbucket)\lesson_3\read.txt";
Удалил

2024-04-11 15:14 UTC, C0rnFl0wer commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    delete New_Arrr_of_Numbers;
исправил

2024-04-11 15:15 UTC, C0rnFl0wer commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +int main()
![изображение_2024-04-11_172756455](https://github.com/russov/Md-CD1-30-24/assets/164394522/81ec3f05-eb49-4c38-b42f-aa1a6b35b1c5)
Не согласен, все работает, на скрине пример.

2024-04-15 10:54 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    int SIZE;
исправления не закоммичены

2024-04-15 10:54 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    ofstream Lesson_3;
исправления не закоммичены

2024-04-15 10:54 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    //string path = "D:\git_(trashbucket)\lesson_3\read.txt";
исправления не закоммичены

2024-04-15 10:54 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    delete New_Arrr_of_Numbers;
исправления не закоммичены

2024-04-15 10:55 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +int main()
Согласен. все тут работает.

2024-04-15 19:02 UTC, C0rnFl0wer commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    //string path = "D:\git_(trashbucket)\lesson_3\read.txt";
https://github.com/russov/Md-CD1-30-24/pull/28/commits/af8cfff35eaa8ef92fde15e6683162596bb60cc3, странно, но я вроде как закоммитил, ссылка сверху
![изображение_2024-04-15_220205269](https://github.com/russov/Md-CD1-30-24/assets/164394522/67497d9d-dd95-447d-9e0d-7d1e6cccb137)

2024-04-15 22:37 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    //string path = "D:\git_(trashbucket)\lesson_3\read.txt";
в этом коммите была залита следующая домашка про фигурные скобки и массивы. А исправления домашки про работу с файлами нету. Проверь, пожалуйста, может не туда залил или пуш не нажал.

2024-04-15 22:42 UTC, russov commented on Vasilij_Kluev/HW_Lesson_3/HW_Lesson_3.cpp
> +    //string path = "D:\git_(trashbucket)\lesson_3\read.txt";
я нашел куда скорее всего залиты изменения: Lesson_3_kluev_vasilij, но там нет пул реквеста. можно подлить сюда все изменения оттуда и я тут проверю.

2024-04-22 12:01 UTC, russov requested changes

2024-04-22 12:01 UTC, russov commented on Vasilij_Kluev/hw3_arr_10_10_check_braces/test_Arr_10_10/test_Arr_10_10/Source.cpp
> +	int first_Nunber_of_arr = arr[0][0];
Старайся придерживаться одного стиля в приложении. после _ большая буква или маленькая?

2024-04-22 12:07 UTC, russov commented
Вторую задачу я принял и смержил в другой ветке. Исправь здесь только третью задачу

2024-07-02 08:40 UTC, russov approved these changes

2024-07-02 08:40 UTC, merged