Task1_Kostya Timoshenko
russov/Md-CD1-30-24 pull request #31
Opened 2024-04-03 11:20 UTC by KostyaTimoshenko

2024-04-08 21:31 UTC, russov requested changes

2024-04-09 00:32 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task1/Task1.cpp
> +	if (ofile == 'y' || ofile == 'Y') { // Если перезаписать
Исправил если правильно понял, добавил функцию void outfile и вызываю её в main. Так же убрал большое условия while, сделал true, и обрываю цикл только когда будет ответ.

2024-04-09 00:37 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task1/Task1.cpp
> +	while (inf >> a)
Пытался сделать count глобальной переменной и считать сколько раз ввел значения, но тогда не работает функция не перезаписывать файл, знаю что можно сделать через вектор, но боюсь что все испорчу. Так как потом массив строится от count, не знаю как реализовать по другому. Так же там было третье замечание, по поводу памяти, я так понимаю это по поводу массива, я добавил освобождение памяти в конце main. Я просто что то нажал и пропало третье замечание.

2024-04-15 11:14 UTC, russov approved these changes

2024-04-15 11:14 UTC, merged