Completed both tasks in different files
russov/Md-CD1-30-24 pull request #35
Opened 2024-04-06 10:07 UTC by waldemurr

Выполнил третье домашнее задание с использование текущего пройденного материала

2024-04-22 10:37 UTC, russov requested changes

2024-04-22 10:37 UTC, russov commented on Vladimir_Shedzko/Lesson 5/task3_2.cpp
> +        out << "File is incorrect";
Невнимательно прочитал условие). Надо результат продублировать на экран

2024-04-22 10:37 UTC, russov commented on Vladimir_Shedzko/Lesson 5/task3_2.cpp
> +    // std::string content(std::istreambuf_iterator<char>{inp}, {});
в коде не должно быть таких комментарием

2024-04-22 10:37 UTC, russov commented on Vladimir_Shedzko/Lesson 5/task3_1.cpp
> +    int a, b, minRow, minEl;
Лучше объявлять переменные каждая на новой строке и инициализировать начальным значение по умолчанию, для int это "0", иначе переменные будут хранить мусор, что иногда может привести к проблемам.

2024-04-26 17:52 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 5/task3_2.cpp
> +        out << "File is incorrect";
Сделал аналогичный консольный вывод

2024-04-26 17:53 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 5/task3_2.cpp
> +    // std::string content(std::istreambuf_iterator<char>{inp}, {});
комментарий убран

2024-04-26 17:53 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 5/task3_1.cpp
> +    int a, b, minRow, minEl;
перенёс переменную в новую строку каждую и задал значение 0 по умолчанию

2024-04-29 11:38 UTC, russov approved these changes

2024-04-29 11:38 UTC, merged