task3
russov/Md-CD1-30-24 pull request #38
Opened 2024-04-08 13:47 UTC by ArtyomBelnev

Task3

2024-04-22 11:11 UTC, russov requested changes

2024-04-22 11:11 UTC, russov commented on Artyom_Belnev/Task_3/main.cpp
> +//void getOutArr(int arr[][COLS]) {
const

2024-04-22 11:11 UTC, russov commented on Artyom_Belnev/Task_3/main.cpp
> +//	while (checkNumber == false) {
while (!checkNumber)

2024-04-22 11:11 UTC, russov commented on Artyom_Belnev/Task_3/main.cpp
> +//int isCheckNumber(char x) {
по названию эта функция просто проверяет переменную. А на самом деле еще и читает консоль. Здесь несоответствие названия с решаемой задачей.

2024-04-22 11:11 UTC, russov commented on Artyom_Belnev/Task_3/main.cpp
> +//	for (int col = 0; col < COLS; ++col) {
Есть ли тут способ проще? Без поэлементного копирования.

2024-04-23 18:44 UTC, ArtyomBelnev commented on Artyom_Belnev/Task_3/main.cpp
> +//	for (int col = 0; col < COLS; ++col) {
не совсем понимаю вопрос , это обычный цикл в котором делается свап

2024-04-29 11:48 UTC, russov approved these changes

2024-04-29 11:48 UTC, merged