Task3_KostyaTimoshenko
russov/Md-CD1-30-24 pull request #42
Opened 2024-04-09 23:06 UTC by KostyaTimoshenko

дз_3

2024-04-13 07:33 UTC, waldemurr reviewed
Всё работает, и зачастую правильно, но попробуй писать более сжатый код

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3/Task3.sln
добавить в гитигнор

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3/Task3.vcxproj
добавить в гитигнор

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3/Task3.vcxproj.filters
добавить в гитигнор

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3/Task3_1.cpp
комментарии лучше на английском
сейчас сломана кодировка

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3/Task3_1.cpp
> +void swap_s(int arr[10][10], int str1, int str2) //������� ��� ����� ����� �������
магические числа

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3/Task3_1.cpp
> +	min = mass[0][0];
`int min = mass[0][0];`
можно сразу

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3/Task3_1.cpp
> +		}
может лучше с табуляцией?

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3_2/Task3_2.cpp
> +	readf.close(); //������� ����
сейчас файл

```
#include <iostream>
 }int main()
    }} std::cout << "Fail" << std::endl; {{
{ 
```
выдаст true

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3_2/Task3_2.vcxproj
в гитигнор

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3_2/Task3_2.vcxproj.filters
в гитигнор

2024-04-13 07:33 UTC, waldemurr commented on Kostya_Timoshenko/Task3_2/c.txt
> +		sum = sum + mas[i];
почему бы не сделать всё за один проход

2024-04-13 10:28 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3/Task3.sln
Добавил в гитигнор, но пришлось удалять уже залитые в пул реквест мусорные файлы

2024-04-13 10:29 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3/Task3.vcxproj
Добавил в гитигнор, но пришлось удалять уже залитые в пул реквест мусорные файлы

2024-04-13 10:29 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3/Task3.vcxproj.filters
Добавил в гитигнор, но пришлось удалять уже залитые в пул реквест мусорные файлы

2024-04-13 11:19 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3/Task3_1.cpp
Исправил

2024-04-13 11:19 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3/Task3_1.cpp
> +void swap_s(int arr[10][10], int str1, int str2) //������� ��� ����� ����� �������
Исправил

2024-04-13 11:20 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3/Task3_1.cpp
> +	min = mass[0][0];
Если я правильно понял, что ты предлагаешь, ломается то что я хотел сделать, если несколько минимальных элементов, тогда они меняются по очереди с первой строкой, а если сделать, как ты, то только высшую строку с минимальный элементом меняет один раз, можно сделать через вектор, но пока не использую вектора

2024-04-13 11:21 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3/Task3_1.cpp
> +		}
Пробовал, выглядит на мой взгляд хуже, вывел в отдельную функцию оформление, что бы меньше места занимало

2024-04-13 11:21 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3_2/Task3_2.cpp
> +	readf.close(); //������� ����
Тут немного не понял, про что ты

2024-04-13 11:21 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3_2/Task3_2.vcxproj
Добавил

2024-04-13 11:21 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3_2/Task3_2.vcxproj.filters
Добавил

2024-04-13 11:23 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3_2/c.txt
> +		sum = sum + mas[i];
for (int i = count - 1; i >= 0; i--) {//Mirroring and sum
		std::cout << mas[i] << " ";
		sum += mas[i];
	}
	Это первая домашка, можно так

2024-04-22 13:16 UTC, russov requested changes

2024-04-22 13:16 UTC, russov commented on Kostya_Timoshenko/Task3_2/Task3_2.cpp
> +				count++;
Надо давать более понятные названия переменной

2024-04-22 13:19 UTC, russov commented
Обрати внимание что здесь конфликт и такой код не смержится

2024-04-24 14:11 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3/Task3_1.cpp
> +	int min = 0;
Исправил

2024-04-24 14:12 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3/Task3_1.cpp
> +	if (g_array < 10)
Исправил

2024-04-24 14:12 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3_2/Task3_2.cpp
> +				count++;
Исправил

2024-04-24 14:26 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task3/Task3_1.cpp
> +				swap_s(arr, 0, i);
Так и задумывал, мне показалось, это лучше чем менять только одну строку, если же их несколько то меняем по очереди каждую. Если менять только одну строку с минимальным элементом то непонятно какую, если строку которая выше остальных с минимальным элементом, то почему именно её, а не третью или вторую, Решил сделать реализовать такой вариант.

2024-04-29 11:57 UTC, russov approved these changes

2024-04-29 11:57 UTC, merged