Task3 kebets
russov/Md-CD1-30-24 pull request #43
Opened 2024-04-10 10:44 UTC by kebetsV

2024-04-13 07:51 UTC, waldemurr reviewed
Хорошо, ещё бы гитигнор настроить

2024-04-13 07:51 UTC, waldemurr commented on Vladislav_Kebets/task3/task3.2/task3.2.sln
в гитигнор

2024-04-13 07:51 UTC, waldemurr commented on Vladislav_Kebets/task3/task3.2/task3.2/task3.2.cpp
> +            else if (sym == '}')--count;
добавь проверку
```
if (counter < 0){
    // do smtn for false result
}
```
сейчас файл 
```
#include <iostream>
 }int main()
    }} std::cout << "Fail" << std::endl; {{
{ 
```
выдаст true

2024-04-13 07:51 UTC, waldemurr commented on Vladislav_Kebets/task3/task3.2/task3.2/task3.2.vcxproj
в гитигнор

2024-04-13 07:51 UTC, waldemurr commented on Vladislav_Kebets/task3/task3.2/task3.2/task3.2.vcxproj.filters
в гитигнор

2024-04-13 07:51 UTC, waldemurr commented on Vladislav_Kebets/task3/task3/task3.sln
в гитигнор

2024-04-13 07:51 UTC, waldemurr commented on Vladislav_Kebets/task3/task3/task3/task3.cpp
> +void PrintArray(int arr[][10]) {
название функции с маленькой буквы

2024-04-13 07:51 UTC, waldemurr commented on Vladislav_Kebets/task3/task3/task3/task3.vcxproj
в гитигнор

2024-04-13 07:51 UTC, waldemurr commented on Vladislav_Kebets/task3/task3/task3/task3.vcxproj.filters
в гитигнор

2024-04-15 16:40 UTC, russov commented on Vladislav_Kebets/task3/task3.2/task3.2/task3.2.vcxproj
Это тоже надо, чтобы запустить на другом компьютере

2024-04-15 16:40 UTC, russov commented on Vladislav_Kebets/task3/task3/task3.sln
не надо.

2024-04-15 16:40 UTC, russov commented on Vladislav_Kebets/task3/task3/task3/task3.vcxproj
не надо

2024-04-15 16:45 UTC, russov commented
Обрати внимание, что у тебя конфликт, такой реквест смержить не получиться. Скорее всего патаешься закоммитить тот же код который уже есть.

2024-04-15 22:06 UTC, russov requested changes

2024-04-15 22:06 UTC, russov commented on Vladislav_Kebets/task3/task3.2/task3.2/task3.2.cpp
> +}
не закрывается работа с файлами

2024-04-16 16:57 UTC, kebetsV commented
конфликт я убрал, но вместе с этим в file changed изменились файлы которые я вроде никогда и не трогал.... Даже не знаю, то ли я сделал

2024-04-19 20:51 UTC, russov requested changes

2024-04-19 20:51 UTC, russov commented on Yury_Rusovich_Trener/Lesson 3/HW_2/HW_2/HW_2.vcxproj
Пытаешься закоммитить в чужую папку

2024-04-19 20:51 UTC, russov commented on evgeny_lauman/task2/task2.vcxproj.filters
Пытаешься закоммитить в чужую папку

2024-04-20 16:51 UTC, kebetsV commented on Yury_Rusovich_Trener/Lesson 3/HW_2/HW_2/HW_2.vcxproj
файлы сами изменились когда я разбирался с конфликтом, так и не понял почему, но сейчас вроде все исправил

2024-04-29 12:15 UTC, merged