Complite task3
russov/Md-CD1-30-24 pull request #46
Opened 2024-04-10 15:25 UTC by cherrySunset

2024-04-13 07:48 UTC, waldemurr reviewed
настрой .gitignore - не плоди мусор

2024-04-13 07:48 UTC, waldemurr commented on Alexandr_Kartavitsky/task3/.vscode/settings.json
в гитигнор

2024-04-13 07:48 UTC, waldemurr commented on Alexandr_Kartavitsky/task3/.vscode/tasks.json
в гитигнор

2024-04-13 07:48 UTC, waldemurr commented on Alexandr_Kartavitsky/task3/check_brackets.h
а вот использование стека - хорошая практика

2024-04-13 07:48 UTC, waldemurr commented on Alexandr_Kartavitsky/task3/task3.cpp
> +            arr[i][j] = rand() % 50;
а чего только 50?

2024-04-13 07:48 UTC, waldemurr commented on Alexandr_Kartavitsky/task3/.vscode/launch.json
в гитигнор

2024-04-13 07:48 UTC, waldemurr commented on Alexandr_Kartavitsky/task3/.vscode/c_cpp_properties.json
в гитигнор

2024-04-13 07:48 UTC, waldemurr commented on Alexandr_Kartavitsky/cpptask2/write_endd_file.h
> +return 1;
зачем везде возвращать 1?
сделай void функцию тогда уже

2024-04-13 07:48 UTC, waldemurr commented on Alexandr_Kartavitsky/cpptask2/.gitignore.txt
в гитигнор

2024-04-22 14:37 UTC, russov requested changes

2024-04-22 14:37 UTC, russov commented on Alexandr_Kartavitsky/task3/task3.cpp
> +    const int x = 5, y = 5;
почему 5. по условия 10

2024-04-22 14:37 UTC, russov commented on Alexandr_Kartavitsky/task3/check_brackets.h
почему это реализовано в h файле?

2024-07-02 08:11 UTC, russov approved these changes

2024-07-02 08:11 UTC, merged