Salnikov_Task3
russov/Md-CD1-30-24 pull request #48
Opened 2024-04-13 07:02 UTC by Ri4ardsal

2024-04-13 07:40 UTC, waldemurr reviewed
Есть вопросы по стилистике
Проверку скобок лучше переделать

2024-04-13 07:40 UTC, waldemurr commented on Vlad_Salnikov/Task3/first_point_of_the_task/Task3.sln
в гитигнор

2024-04-13 07:40 UTC, waldemurr commented on Vlad_Salnikov/Task3/first_point_of_the_task/Task3.vcxproj
в гитигнор

2024-04-13 07:40 UTC, waldemurr commented on Vlad_Salnikov/Task3/first_point_of_the_task/Task3.vcxproj.filters
в гитигнор

2024-04-13 07:40 UTC, waldemurr commented on Vlad_Salnikov/Task3/second_point_of_the_task/Task3file.sln
в гитигнор

2024-04-13 07:40 UTC, waldemurr commented on Vlad_Salnikov/Task3/second_point_of_the_task/Task3file.vcxproj
в гитигнор

2024-04-13 07:40 UTC, waldemurr commented on Vlad_Salnikov/Task3/second_point_of_the_task/Task3file.vcxproj.filters
в гитигнор

2024-04-13 07:40 UTC, waldemurr commented on Vlad_Salnikov/Task3/second_point_of_the_task/out.txt
сломана кодировка - выводи на английском

2024-04-13 07:40 UTC, waldemurr commented on Vlad_Salnikov/Task3/second_point_of_the_task/point2.cpp
> +			if (str[i] == '{' || str[i] == '}')
Сейчас этот файл закроет все скобки:
```
#include <iostream>
 }int main()
    }} std::cout << "Fail" << std::endl; {{
{ 
```
И даже этот
```
#include <iostream>
 int main()
    {{ std::cout << "Fail" << std::endl; {{

```

2024-04-13 07:40 UTC, waldemurr commented on Vlad_Salnikov/Task3/second_point_of_the_task/point2.cpp
> +	fileOUT.open("out.txt", std::ios::out);
капсом переменные не принято называть

2024-04-13 07:40 UTC, waldemurr commented on Vlad_Salnikov/Task3/first_point_of_the_task/point1.cpp
> +			std::cout << array[i][k] << ' ';
почему бы сразу его и не вывести - избавишься от одного цикла

2024-04-22 14:24 UTC, russov requested changes

2024-04-22 14:24 UTC, russov commented on Vlad_Salnikov/Task3/first_point_of_the_task/point1.cpp
> +	int a;
инициализация начальным значением

2024-04-22 14:24 UTC, russov commented on Vlad_Salnikov/Task3/first_point_of_the_task/point1.cpp
> +	int array[10][10];
магические числа, лучше создать константу для хранения 10 и использовать везде

2024-04-22 14:24 UTC, russov commented on Vlad_Salnikov/Task3/first_point_of_the_task/point1.cpp
> +			num = array[0][i];
int num = array[0][i];

2024-04-29 12:19 UTC, russov approved these changes

2024-04-29 12:20 UTC, merged