Task 4 Vladimir Shedzko
russov/Md-CD1-30-24 pull request #49
Opened 2024-04-13 21:01 UTC by waldemurr

Добавил базовую работу со словарями. Можно конечно было запариться и свести вероятность вытягивания карты к реальной, но едва ли суть задачи была в этом, потому максимально упрощённый вариант.

2024-04-25 07:47 UTC, Ri4ardsal commented
Есть магические числа, например 17. Можно вынести в константу minDealerValue, наверное)

2024-04-27 09:55 UTC, waldemurr commented
исправлено

2024-04-27 09:56 UTC, waldemurr commented
> Есть магические числа, например 17. Можно вынести в константу minDealerValue, наверное)

исправлено

2024-05-19 10:08 UTC, russov requested changes

2024-05-19 10:08 UTC, russov commented on Vladimir_Shedzko/Lesson 7/task_4_1.cpp
> +    bool player_end;
почему бы это не перенести внутрь while.
const auto player_end{ checkForEnd(&player_sum, player_last, player_cnt) };
ради улучшения читабельности кода, можно пренебречь выделением памяти под такой тип как bool

2024-05-19 10:08 UTC, russov commented on Vladimir_Shedzko/Lesson 7/task_4_1.cpp
> +    std::stack<int> player_cards;
начальная инициализация.  std::stack<int> player_cards{}

2024-05-19 10:08 UTC, russov commented on Vladimir_Shedzko/Lesson 7/task_4_1.cpp
> +    int dealer_last = drawCard();
везде лучше использовать
auto dealer_last{ drawCard() }
если переменная константная то добавлять еще и cost

2024-05-19 10:08 UTC, russov commented on Vladimir_Shedzko/Lesson 7/task_4_1.cpp
> +            std::cout << "Wrong input: " << curchar << std::endl;
лучше везде использовать {}
или хотя бы одинаково во всем проекте

2024-05-19 21:43 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 7/task_4_1.cpp
> +    int card = std::rand()%(card_max - card_min + 1) + card_min;
> Может здесь do/while поможет?
сделано
> лучше будет сделать auto card{ ... };
не думаю, что auto - панацея от всего
+ если делать так, то card не попадёт в область видимости while

2024-05-19 21:47 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 7/task_4_1.cpp
> +    int dealer_last = drawCard();
сделано
переменная не константная, потому const не добавлен

2024-05-19 21:49 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 7/task_4_1.cpp
> +            std::cout << "Wrong input: " << curchar << std::endl;
добавлены везде

2024-05-19 21:50 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 7/task_4_1.cpp
> +    std::stack<int> player_cards;
сделано

2024-05-19 21:50 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 7/task_4_1.cpp
> +    if (amount > 21){
исправлено

2024-05-19 21:51 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 7/task_4_1.cpp
> +    bool player_end;
сделано

2024-07-01 10:35 UTC, russov approved these changes

2024-07-01 10:35 UTC, merged