Task 4 Black-Jack by Kluev
russov/Md-CD1-30-24 pull request #57
Opened 2024-04-21 11:40 UTC by C0rnFl0wer

2024-04-21 15:35 UTC, Ri4ardsal reviewed
Используй переводчик или словарь, если пишешь названия на английском, то пиши на английском правильно. Названия переменных не соответствуют их назначению.

2024-04-21 15:35 UTC, Ri4ardsal commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +int Count_value_of_card(int)
Могу ошибаться, исправьте если не прав. Во первых sicle это сосулька, cycle - круг, цикл.
Во вторых, здесь не нужен bool sicle, здесь делаешь бесконечный цикл, while(true), и вместо вот этой штуки:
break;
sicle = false;
пишешь:
return card_value.

2024-04-21 15:35 UTC, Ri4ardsal commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +	std::cin >> plaer_answer_2;
Зачем ты вообще создавал переменные Y, N и другие?
Создай одну переменную plaer_answer_2, а потом просто сравнивай значение в этой переменной с условием и все.

2024-04-21 15:35 UTC, Ri4ardsal commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +	std::cout << "Yor value is: " << value_of_plaer_hend << "\n" << "What do you want to do now?\n" << "enter 'hite' if you whonna kip new card or 'stend' if you wonna end the game \n";
Могу ошибаться, но вроде так делать не надо. На несколько cout надо разбивать.

2024-04-21 15:35 UTC, Ri4ardsal commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +	std::cin >> plaer_answer_2;
И да plaYer, а не plaer.

2024-04-21 15:35 UTC, Ri4ardsal commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +int value_of_diller_hend = 0, value_of_plaer_hend = 0, card_value = 0, temp = 0, temp2 = 0;
Dealer а не diller.
Dealer - [дийлар] - в дословном переводе и в блекджеке - Дилер. Это сотрудник казино, играющий против других игроков от лица игорного дома. Термин используется и в других азартных играх. Дилер раздаёт карты, принимает ставки, в случае победы игрока выдаёт ему выигрыш.

2024-04-21 15:35 UTC, Ri4ardsal commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +		std::cout << "Diller pik app next card: \n";
pik переводится как пик, piCk - выбирать.
В данном случае лучше использовать: dealer take card.
Используй переводчик.

2024-04-21 18:10 UTC, C0rnFl0wer commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +int value_of_diller_hend = 0, value_of_plaer_hend = 0, card_value = 0, temp = 0, temp2 = 0;
@Ri4ardsal , замечания по грамматике я учел, спасибо большое!

2024-04-21 18:11 UTC, C0rnFl0wer commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +	for (int i = 0; i < Deck_size; ++i) {
@Ri4ardsal, спасибо, учел.

2024-04-21 18:16 UTC, C0rnFl0wer commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +void Show_card()
@Ri4ardsal, спасибо, но я слышал, что бесконечные циклы это не очень хорошо и лучше иметь инструмент  выхода из цикла. Дождусь ответа Юрия, если он подтвердит, тогда поправлю)

2024-04-21 18:16 UTC, C0rnFl0wer commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +int Count_value_of_card(int)
@Ri4ardsal, спасибо, но я слышал, что бесконечные циклы это не очень хорошо и лучше иметь инструмент выхода из цикла. Дождусь ответа Юрия, если он подтвердит, тогда поправлю)

2024-04-21 18:18 UTC, C0rnFl0wer commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +void Show_card()
@Ri4ardsal, возможно ты прав, но так тоже вроде работает нормально. Если Юрий скажет, поправлю)

2024-04-21 18:21 UTC, C0rnFl0wer commented on Vasilij_Kluev/BlackJeck/BlackJeck.cpp
> +	std::cout << "Yor value is: " << value_of_plaer_hend << "\n" << "What do you want to do now?\n" << "enter 'hite' if you whonna kip new card or 'stend' if you wonna end the game \n";
@Ri4ardsal, если честно, то не вижу ничего плохого в этой записи, но я могу ошибаться. На будущее учту.

2024-05-19 11:01 UTC, russov requested changes

2024-07-02 08:37 UTC, russov approved these changes

2024-07-02 08:38 UTC, merged