Task4 kebets
russov/Md-CD1-30-24 pull request #59
Opened 2024-04-22 17:35 UTC by kebetsV

2024-04-24 04:40 UTC, waldemurr reviewed
всё класс, неплохой интерфейс

2024-04-24 04:40 UTC, waldemurr commented on Vladislav_Kebets/task4/blackjack.sln
в гитигнор

2024-04-24 04:40 UTC, waldemurr commented on Vladislav_Kebets/task4/blackjack/blackjack.cpp
> +    ACE = 14
у карт не такие значения

2024-04-24 04:40 UTC, waldemurr commented on Vladislav_Kebets/task4/blackjack/blackjack.cpp
> +    bool bet_is_ok = 1;
лучше без неявного преобразования типов

2024-04-24 04:40 UTC, waldemurr commented on Vladislav_Kebets/task4/blackjack/blackjack.vcxproj
в гитигнор

2024-04-24 04:40 UTC, waldemurr commented on Vladislav_Kebets/task4/blackjack/blackjack.vcxproj.filters
в гитигнор

2024-05-19 11:23 UTC, russov requested changes

2024-05-19 11:23 UTC, russov commented on Vladislav_Kebets/task4/blackjack/blackjack.cpp
> +    std::array<int, CARD_AMOUNT> deck{ 2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,9,9,9,9,10,10,10,10,JACK,JACK,JACK,JACK,QUEEN,QUEEN,QUEEN,QUEEN,KING,KING,KING,KING,ACE,ACE,ACE,ACE };
старайся избегать таких длинных строк. переноси на новую строчку. Это не ошибка, немного ухудшает читабельность

2024-05-19 11:23 UTC, russov commented on Vladislav_Kebets/task4/blackjack/blackjack.cpp
> +    int used_cards = 0;
auto used_cards{ 0 }, если переменная константная то надо добавлять const

2024-05-19 11:23 UTC, russov commented on Vladislav_Kebets/task4/blackjack/blackjack.cpp
> +                if (player_sum > 21) {
Магическое число

2024-05-19 11:23 UTC, russov commented on Vladislav_Kebets/task4/blackjack/blackjack.cpp
> +            case'1':
магическое число

2024-05-19 11:23 UTC, russov commented on Vladislav_Kebets/task4/blackjack/blackjack.cpp
> +        bool player_turn = 1;
неявное преобразование int и bool

2024-05-19 11:23 UTC, russov commented on Vladislav_Kebets/task4/blackjack/blackjack.cpp
> +void printGameInformation(std::vector<int>& dealer_cards, int dealer_sum, std::vector<int>& player_cards, int player_sum, int used_cards, int bet);
Все переменные которые не модифицируются должны быть константными

2024-05-19 11:23 UTC, russov commented on Vladislav_Kebets/task4/blackjack/blackjack.cpp
> +    for (int card : someone_cards) {
const auto

2024-05-19 11:23 UTC, russov commented on Vladislav_Kebets/task4/blackjack/blackjack.cpp
> +void giveCard(std::vector<int>& someone_cards, int& used_cards, std::array<int, CARD_AMOUNT>& deck, int& someone_sum) {
В целом здесь все ок, но много переменных которые передаются по ссылке и модифицируются внутри функции, это потенциальные ошибки и усложнения в понимании приложения.

2024-07-02 08:36 UTC, merged