Task 4 Alexandra Nikitina
russov/Md-CD1-30-24 pull request #60
Opened 2024-04-24 13:50 UTC by minaikas

Added task 4 with blackjack game

2024-04-24 15:42 UTC, waldemurr reviewed
Очень классный вывод и красивая структура. Стоит чуть аккуратнее расписать условия ничьей

2024-04-24 15:42 UTC, waldemurr commented on Alexandra_Nikitina/task_4/task_4.cpp
> +    if(PlayersSum > 21){
если у дилера тоже перебор, то это ничья

2024-04-25 07:59 UTC, Ri4ardsal commented on Alexandra_Nikitina/task_4/task_4.cpp
> +    if(PlayersSum > 21){
Такой ситуации не может быть. Правила блэкджека не допускают такой ситуации. Игроки с перебором вылетают сразу, а с дилером играют только те у кого 21 и меньше.

2024-05-20 10:22 UTC, russov requested changes

2024-05-20 10:22 UTC, russov commented on Alexandra_Nikitina/task_4/task_4.cpp
> +main(){
int main

2024-05-20 10:22 UTC, russov commented on Alexandra_Nikitina/task_4/task_4.cpp
> +    return;
здесь return лишний

2024-05-20 10:22 UTC, russov commented on Alexandra_Nikitina/task_4/task_4.cpp
> +    if(PlayersSum > 21){
магически числа

2024-05-20 10:22 UTC, russov commented on Alexandra_Nikitina/task_4/task_4.cpp
> +    int PlayersCardOne = TakeCard(cards);
const auto PlayersCardOne{ TakeCard(cards) };
Все что не меняется должно быть const

2024-05-20 10:22 UTC, russov commented on Alexandra_Nikitina/task_4/task_4.cpp
> +    while (PlayersChoise == "hit" || PlayersChoise == "Hit"){
std::tolower или std::toupper

2024-07-02 08:33 UTC, russov approved these changes

2024-07-02 08:33 UTC, merged