Salnikov_task4
russov/Md-CD1-30-24 pull request #61
Opened 2024-04-24 14:14 UTC by Ri4ardsal

2024-04-24 16:01 UTC, waldemurr reviewed
Интересный ООП подход, замечания как раз в основном по нему

2024-04-24 16:01 UTC, waldemurr commented on Vlad_Salnikov/task4BlackJack/Player.h
> +	void resetHandAndValues();
лучше просто resetHand, а потом вызвать ещё и resetValue

2024-04-24 19:24 UTC, Ri4ardsal commented on Vlad_Salnikov/task4BlackJack/Player.h
> +	std::vector <std::string> hand_;
Да, ты прав, возможно было реализовать через стек, но тогда надо будет полностью переписывать код. У меня идет реализация доступа с первого элемента. И еще что бы вывести весь стек, надо вывести последний и затем его удалить. Ну я считаю что проще работать с вектором в данном случае. Но за идею спасибо!) В следующий раз буду иметь ввиду)

2024-04-24 19:24 UTC, Ri4ardsal commented on Vlad_Salnikov/task4BlackJack/Blackjack.cpp
> +			if (player.getValue() > blackjack)
Не совсем так, т.к. мы делаем упрощенную версию, то я реализовал так:
1) Первым циклом идет игрок, если у него перебор то end game, и диллер не берет карту. 
2) Диллер делает тоже самое и работает по тому же принципу. Если перебор то сразу end game.
С точки зрения приближенной к реальности, ты прав, но исходя из ТЗ не совсем)
//
если у игрока в результате получается больше 21, то он проиграл;

   ход дилера выполняется после хода игрока;

   дилер берет карты до тех пор, пока его общий результат не достигнет 17 или более очков. Как только этот предел достигнут — дилер карт уже не берет;

   если у дилера больше 21-го, то дилер проиграл, а игрок победил;
   если же у дилера и у игрока до 21 очка, то выигрывает тот, у кого результат больше.

2024-05-20 10:58 UTC, russov requested changes

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Player.h
> +	void setValue(int);
здесь лучше писать название переменной которая будет передаваться во входном пареметре, чтобы когда будешь читать хеадер файл сразу становилось понятно что тут происходит

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Player.cpp
> +	Player::value_ += cardValue;
зачем тут Player::? Это все верно, но когда пишешь код надо делать так чтобы оформление было одинаковое везде.

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Player.cpp
> +void Player::setHand(std::string card)
const &

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Player.cpp
> +	std::string name;
std::cin >> _name;
Почему бы не сделать так? чтоб было проще

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Player.cpp
> +Player::Player(std::string name)
const &

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Blackjack.cpp
> +			for (auto n: dealer.getHand())
const auto

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Blackjack.cpp
> +			if (choice == 2)
Любое значение не равное 2 и 0 приравниваются к 1.

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Blackjack.cpp
> +int input(int num)
в чем смысл передавать num если переменная сразу же перезаписывается?

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Blackjack.cpp
> +			int newGameChoice{ 0 };
auto newGameChoice{ input() }

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Blackjack.cpp
> +			while (newGameChoice != 0 && newGameChoice != 1)
Лучше заменить на do\while чтобы не вызывать функцию  input дважды

2024-05-20 10:58 UTC, russov commented on Vlad_Salnikov/task4BlackJack/Blackjack.cpp
> +			if (newGameChoice == 1)
if (!newGameChoice){
    return 0;
}
continue;

такой код встречается много где и он выглядит громоздким, попробуй его переделать, чтоб все выглядело красиво

2024-06-05 13:27 UTC, russov approved these changes

2024-06-05 13:27 UTC, merged