Task4
russov/Md-CD1-30-24 pull request #62
Opened 2024-04-24 15:30 UTC by KostyaTimoshenko

Домашнее задание 4

2024-04-24 15:48 UTC, waldemurr reviewed
Неплохо сделано, но есть вопросы по оформлению кода и оптимизации

2024-04-24 15:48 UTC, waldemurr commented on Kostya_Timoshenko/Task4/Task4.cpp
> +			PlayerCards.push_back(Card);
стоит хранить сумму в отдельной переменной, а не считать каждый раз сумму в деке

2024-04-24 15:48 UTC, waldemurr commented on Kostya_Timoshenko/Task4/Task4.cpp
> +		else if (AnswerQuestion == "stand") {
не стоит хранить постобработку внутри цикла

2024-04-28 21:12 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task4/Task4.cpp
> +			PlayerCards.push_back(Card);
исправил

2024-04-28 21:12 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task4/Task4.cpp
> +		else if (AnswerQuestion == "stand") {
исправил, если я правильно понял что ты

2024-05-20 11:14 UTC, russov requested changes

2024-05-20 11:14 UTC, russov commented on Kostya_Timoshenko/Task4/Task4.cpp
> +	std::string ValueCard = CardTaken.substr(0, CardTaken.size() - 1);
const auto ValueCard{CardTaken.substr(0, CardTaken.size() - 1)};

2024-05-20 11:14 UTC, russov commented on Kostya_Timoshenko/Task4/Task4.cpp
> +	int randomIndex = rand() % DeckCards.size();
{}

2024-05-20 11:14 UTC, russov commented on Kostya_Timoshenko/Task4/Task4.cpp
> +	std::string AnswerQuestion;
std::string AnswerQuestion{}

2024-05-20 11:14 UTC, russov commented on Kostya_Timoshenko/Task4/Task4.cpp
> +	std::vector<std::string> DeckCards;
std::vector<std::string> DeckCards{}

2024-05-21 02:57 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task4/Task4.cpp
> +	std::string ValueCard = CardTaken.substr(0, CardTaken.size() - 1);
Исправил

2024-05-21 02:57 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task4/Task4.cpp
> +	std::string AnswerQuestion;
Исправил

2024-05-21 02:57 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task4/Task4.cpp
> +	std::vector<std::string> DeckCards;
Исправил

2024-05-21 02:57 UTC, KostyaTimoshenko commented on Kostya_Timoshenko/Task4/Task4.cpp
> +	int randomIndex = rand() % DeckCards.size();
Исправил

2024-06-05 13:29 UTC, russov approved these changes

2024-06-05 13:29 UTC, merged