Task5 mahnach
russov/Md-CD1-30-24 pull request #66
Opened 2024-05-03 18:14 UTC by Ms-maria

2024-06-05 14:24 UTC, russov requested changes

2024-06-05 14:24 UTC, russov commented on Mariya_Mahnach/task5/task5/task5/MyString.cpp
> +		delete ptr;
ptr это локальная переменная, которая является указателем, но под нее не выделяется память, как тут можно делать ++ по памяти которая не выделена

2024-06-05 14:26 UTC, russov commented
1) У меня проект не собрался и я не смог проверить как работает строка
2) похоже, ты не разобралась с указателями, там по всему коду проблемы с работой с указателями

2024-06-07 11:27 UTC, Ms-maria commented
> 1. У меня проект не собрался и я не смог проверить как работает строка
> 
>     2. похоже, ты не разобралась с указателями, там по всему коду проблемы с работой с указателями
> 
>     3. местами мне казалось, что этот код вообще нерабочий и никто его не запускал

Я вроде бы говорила на онлайн занятии, что у меня проект вообще не запускался, я не смогла понять почему, и ты сказал лучше запушить, чтобы можно было поискать ошибки

2024-07-01 10:46 UTC, russov approved these changes

2024-07-01 10:55 UTC, merged