Lesson 11 vladimir shedzko
russov/Md-CD1-30-24 pull request #68
Opened 2024-05-03 22:51 UTC by waldemurr

Tests added for std::string class:
- constructor
- push_back
- size
- find
- resize
- pop_back
- swap
CMake configuration for proper gtest initialization provided.

2024-06-09 22:19 UTC, russov requested changes

2024-06-09 22:19 UTC, russov commented on Vladimir_Shedzko/Lesson 11/src/customString.cpp
> +    data = (char*)realloc(data, sizeof(char) * (newsize));
Совместное использование new и realloc является плохой идеей, поскольку new управляет памятью в стиле C++, вызывая конструкторы/деструкторы, а realloc - C стиле без вызова конструкторов/деструкторов. 
Для управления динамической памятью в C++ лучше использовать либо полностью C++ стиль, либо полностью C стиль, но не смешивать их.

2024-06-12 17:21 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 11/include/customString.h
> +#include <iostream>
исправлен двойной импорт

2024-06-12 17:23 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 11/src/customString.cpp
> +    delete data;
исправлен деструктор

2024-06-12 17:45 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 11/src/customString.cpp
> +    data = (char*)realloc(data, sizeof(char) * (newsize));
исправлено небезопасное выделение

2024-07-01 10:58 UTC, russov approved these changes

2024-07-01 10:58 UTC, merged