add task5 evgeny_lauman
russov/Md-CD1-30-24 pull request #73
Opened 2024-05-04 07:12 UTC by EvgenyRB

2024-06-17 21:49 UTC, russov requested changes

2024-06-17 21:49 UTC, russov commented on evgeny_lauman/task6/String.cpp
> +String::String() : String("")
не понял замысел с вызовом конструктора String(""). Может это и верный подход, но выглядит странно, потому что вызывается конструктор String::String(const char* s) с массивом нулевой длины: выделяется память под один элемент.

2024-06-17 21:49 UTC, russov commented on evgeny_lauman/task6/String.cpp
> +    delete[] str;
проверка на nullptr. стандартом это не описано поэтому могут быть разные поведения если удалить два nullptr

2024-06-17 21:49 UTC, russov commented on evgeny_lauman/task6/String.cpp
> +    std::strcpy(str, st.str);
а в чем смысл конструктора перемещения если здесь все равно копирование?

2024-06-17 21:49 UTC, russov commented on evgeny_lauman/task6/String.cpp
> +    char* temp = new char[len + 1];
насколько я понял логику строки, то внутренний массив str хранится с нул-терминатором. почему тогда массив увеличивается сразу на два символа?

2024-06-17 21:49 UTC, russov commented on evgeny_lauman/task6/String.cpp
> +    String st_string{ st };
лучше всего память выделять как можно ближе к место использования этой памяти. если сработает ексепшен, то память под строку будет выделяться напрасно.

2024-06-17 21:49 UTC, russov commented on evgeny_lauman/task6/String.cpp
> +size_t String::find(const String& st, const size_t index) const
typedef unsigned __int64 size_t; - это без знаковый тип. -1 вернуть не получится

2024-06-17 21:49 UTC, russov commented on evgeny_lauman/task6/String.cpp
> +    if (str[0] == NULL)
здесь сравнивается значение, которое находится в первом элементе массива с null а . в коде нигде не  сетится null. непонятно откуда от тут может появиться. по моим ожиданием необходимо str == NULL, но опять же в коде нигде нул не устанавливается

2024-06-17 21:49 UTC, russov commented on evgeny_lauman/task6/String.cpp
> +const char& String::operator[](int i) const
не очень понял зачем этот метод. и лучше стараться избегать возвращать константные переменные, поскольку для таких объектов не работаем семантика перемещения

2024-06-17 21:49 UTC, russov commented on evgeny_lauman/task6/String.cpp
> +    return (std::strcmp(st1.str, st2.str) == 0);
красиве будет если без 0 записать. return !std::strcmp(st1.str, st2.str);

2024-06-17 21:49 UTC, russov commented on evgeny_lauman/task6/String.cpp
Выглядит так будто никто не запускал этот проект на сборку: не хватает инклудов и тд.

2024-06-18 06:22 UTC, EvgenyRB commented on evgeny_lauman/task6/String.cpp
> +String::String() : String("")
Замысел в том, чтобы, если создам непроинициализированную строку, а потом захочу вывести ее или что-то с ней сделать, то моя строка не будет падать, а будет себя вести как пустая строка. Вряд-ли строку создают, чтобы она просто висела непроинициализированной, рано или поздно там будет значение с нуль байтом на конце, так что не вижу проблемы выделить этот 1 ноль байт сразу при создании

2024-06-18 06:31 UTC, EvgenyRB commented on evgeny_lauman/task6/String.cpp
> +    delete[] str;
не могу придумать пример, где для моей реализации строки будет такое поведение

2024-06-18 06:32 UTC, EvgenyRB commented on evgeny_lauman/task6/String.cpp
> +    std::strcpy(str, st.str);
скопировал значение в новый объект и сделал пустым старый, значение по факту переместилось, смысл как и задумывалось - в перемещении

2024-07-01 11:12 UTC, russov commented on evgeny_lauman/task6/String.cpp
> +    std::strcpy(str, st.str);
смысл перемещения в том что это работает быстро: вместо копирования всего массива, копируется только указатель. я намекал тут на std::move и тд.

2024-07-01 11:14 UTC, russov approved these changes

2024-07-01 11:14 UTC, merged