Salnokov_task8
russov/Md-CD1-30-24 pull request #96
Opened 2024-06-08 07:27 UTC by Ri4ardsal

2024-06-28 11:43 UTC, russov requested changes

2024-06-28 11:43 UTC, russov commented on Vlad_Salnikov/Task8/task8.cpp
> +            itRead++;
мне кажется itRead++; вынести в конец функции и убрать else.

2024-06-28 11:43 UTC, russov commented on Vlad_Salnikov/Task8/Timer.h
> +class Timer
Это не таймер, это просто sleep. в данной реализации нет необходимости выделять отдельный класс timer для реализации sleep

2024-06-28 11:43 UTC, russov commented on Vlad_Salnikov/Task8/task8.cpp
> +    readFinish = true;
что тут с синхронизацией потоков? я вижу эту переменную в двух потоках.

2024-06-28 11:43 UTC, russov commented on Vlad_Salnikov/Task8/task8.cpp
> +        write.stop();
здесь запись происходит не каждые 150 мс, а через 150. То есть если запись в консоль по каким-то причинам займет 1 секунду, то в итоге получиться 1с 150 мс, а не 150 мс как написано в в условии

2024-06-28 15:54 UTC, Ri4ardsal commented on Vlad_Salnikov/Task8/task8.cpp
> +            itRead++;
нет, если убрать, то читает 39 символов, хотя в файле 21.

2024-07-01 11:36 UTC, russov approved these changes

2024-07-01 11:36 UTC, merged