Lesson 19 vladimir shedzko
russov/Md-CD1-30-24 pull request #97
Opened 2024-06-09 10:43 UTC by waldemurr

wrote file two-streams processing

2024-06-28 14:21 UTC, russov commented
Все верно и можно мержить, но проблема в том что тут кроме 19 домашки еще и 16. Скорее всего ты отбранчевался не от мастера а от 16 домашки. Если счас смержить эту ветку, то будет конфликт с 16 домашкой

2024-06-28 14:59 UTC, russov requested changes

2024-06-28 14:59 UTC, russov commented on Vladimir_Shedzko/Lesson 19/main.cpp
> +        while (func(stream, cont, lock, counter)) {
В данной реализации символ читается или записывается не каждые 100 или 150 мс, а 100 мс + время выполнения функции и если функция будет выполняться 100, то получиться что чтение будет происходить каждый 200 мс (100 мс - sleep и 100 мс время выполнения функции)

2024-06-29 10:24 UTC, waldemurr commented on Vladimir_Shedzko/Lesson 19/main.cpp
> +        while (func(stream, cont, lock, counter)) {
удалил лишнюю папку

2024-07-01 11:41 UTC, russov approved these changes

2024-07-01 11:41 UTC, merged